### ISSUE TITLE
Fix up how transform errors are reported to the user

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX_frontend#254]
# Problem
Now that we no longer store error messages in the database, the error reporting in frontend is broken. The function `dump_query_errors` is obsolete and will always raise an exception.

# Approach
The full transformer error log is now stored in ElasticSearch and is visible through the Chicago Kibana instance. It can be accessed through the ServiceX Dashboard, or via a direct [Kibana URL](https://atlas-kibana.mwt2.org:5601/s/servicex/app/dashboards?auth_provider_hint=anonymous1#/view/4f197320-f34e-11ed-a6d8-9f6a16cd6d78?embed=true&_g=()&show-time-filter=true&hide-filter-bar=true)

Users have to know how to navigate through this interface. Ideally they would do a search on the transform request ID and file-id and know how to expand the log entry.

It should be possible to construct a URL that contains the search parameters. The serviceX client should be able to report the files that failed and just output these formatted URLs that users could paste into their browsers to view the error report.

# Tasks
- [x] Explore Kibana and Elasticsearch documentation to understand how to construct the URL
- [x] Modify the ServiceX flask server status message to include a list of failed files along with the formatted URL to view that file's logs
- [x] Modify the client to add the new field to the `TransformStatus` class
- [x] Modify `TransformedResults` to return the list of failed files along with the URL to view the log
- [ ] Add a command `servicex transform failures` with a `-t` argument to specify the request ID. It will print out the failed files along with the link to see the logs

**Comment by gordonwatts** [comment]
@BenGalewsky and @ivukotic  - is there a link we can print out so people can go after the transform error? It would be nice to be able to direct folks to the logs quickly.

**Comment by gordonwatts** [comment]
@talvandaalen - I think we should just remove this method, and if we can find a link to print out, we'll add that in later in another "feature" issue.

**Comment by BenGalewsky** [comment]
> @BenGalewsky and @ivukotic - is there a link we can print out so people can go after the transform error? It would be nice to be able to direct folks to the logs quickly.

We would need a new endpoint for the web service. The Base URL for the elastic search is a flask config option populated by the helm chart

**Comment by gordonwatts** [comment]
@BenGalewsky - cool. Could we add that to the backlog? Once it happens (no rush?) we could implement something in a message here.

@talvandaalen - I think, when this error fires, we should print out the GUID request id and tell the user to look in the logs for this request. That will have to do for now, and will make sure the error logs are at least discoverable.
