### ISSUE TITLE
Load `servicex` configuration from files.

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#57]
As an analyzer or user or developer, I'd like to be able to code up all the configuration information in a file and have the servicex library automatically load that information and not have to specify username or passwords in python code that might get uploaded to public repositories.

## Approach

- Use YAML configuration files
- Have a default distributed and loaded from the package.
- The default will use the normal developer configuration (.e.g. `k8 port-forward` to 5000 and 9000).
- The user can create a YAML file in the current working directory or their home directory
- the YAML file will be called '.servicex'
- This work will only do the authentication and endpoint information: there will be no re-try configurations, etc. That is for a future work item.
- It will be possible to test code even working on a developer's very strange setup (e.g. settings other than the default will be ignored when testing).

## TODO's 

- [x] Get search paths working for all platforms
- [x] Get the `servicex` adaptor working
- [x] Get the `minio` adaptor working
- [x] Update the documentation.
- [x] Make sure the default config file is distributed in the `pypi` package.
- [x] Make sure the default test script will work with the config rather than looking for something from the cmd line.
